//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public Ciudades()
        {
            this.Cantones = new HashSet<Cantones>();
            this.Companias = new HashSet<Companias>();
            this.Proveedores = new HashSet<Proveedores>();
            this.Sucursales = new HashSet<Sucursales>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public int IdProvincia { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual ICollection<Cantones> Cantones { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Companias> Companias { get; set; }
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<Sucursales> Sucursales { get; set; }
    }
}
