//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public Modulos()
        {
            this.Modulos1 = new HashSet<Modulos>();
            this.RolModulos = new HashSet<RolModulos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Modulos> Modulos1 { get; set; }
        public virtual Modulos Modulos2 { get; set; }
        public virtual ICollection<RolModulos> RolModulos { get; set; }
    }
}
