//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Usuarios = new HashSet<Usuarios>();
            this.RolModulos = new HashSet<RolModulos>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual ICollection<RolModulos> RolModulos { get; set; }
    }
}
