//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolModulos
    {
        public int Rol_Id { get; set; }
        public int Modulo_Id { get; set; }
        public string Accion { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
