//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public int Id { get; set; }
        public int IdGrupoEmpresarial { get; set; }
        public int IdCompania { get; set; }
        public int IdDivision { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Interseccion { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public string TelefonoPBX { get; set; }
        public string Telefono2 { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Companias Companias { get; set; }
        public virtual Divisiones Divisiones { get; set; }
        public virtual GruposEmpresarial GruposEmpresarial { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
