//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposProveedor
    {
        public TiposProveedor()
        {
            this.Proveedores = new HashSet<Proveedores>();
            this.TiposProveedor1 = new HashSet<TiposProveedor>();
        }
    
        public int Id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<TiposProveedor> TiposProveedor1 { get; set; }
        public virtual TiposProveedor TiposProveedor2 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
