//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VXERP.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Actividades = new HashSet<Actividades>();
            this.Cantones = new HashSet<Cantones>();
            this.Ciudades = new HashSet<Ciudades>();
            this.Companias = new HashSet<Companias>();
            this.Continentes = new HashSet<Continentes>();
            this.Divisiones = new HashSet<Divisiones>();
            this.GruposEmpresarial = new HashSet<GruposEmpresarial>();
            this.Ocupaciones = new HashSet<Ocupaciones>();
            this.Paises = new HashSet<Paises>();
            this.Parroquias = new HashSet<Parroquias>();
            this.Proveedores = new HashSet<Proveedores>();
            this.Provincias = new HashSet<Provincias>();
            this.ReferenciasBancarias = new HashSet<ReferenciasBancarias>();
            this.ReferenciasComerciales = new HashSet<ReferenciasComerciales>();
            this.Sucursales = new HashSet<Sucursales>();
            this.TiposLocal = new HashSet<TiposLocal>();
            this.TiposProveedor = new HashSet<TiposProveedor>();
            this.Zonas = new HashSet<Zonas>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NombreApellido { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual ICollection<Cantones> Cantones { get; set; }
        public virtual ICollection<Ciudades> Ciudades { get; set; }
        public virtual ICollection<Companias> Companias { get; set; }
        public virtual ICollection<Continentes> Continentes { get; set; }
        public virtual ICollection<Divisiones> Divisiones { get; set; }
        public virtual ICollection<GruposEmpresarial> GruposEmpresarial { get; set; }
        public virtual ICollection<Ocupaciones> Ocupaciones { get; set; }
        public virtual ICollection<Paises> Paises { get; set; }
        public virtual ICollection<Parroquias> Parroquias { get; set; }
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        public virtual ICollection<Provincias> Provincias { get; set; }
        public virtual ICollection<ReferenciasBancarias> ReferenciasBancarias { get; set; }
        public virtual ICollection<ReferenciasComerciales> ReferenciasComerciales { get; set; }
        public virtual ICollection<Sucursales> Sucursales { get; set; }
        public virtual ICollection<TiposLocal> TiposLocal { get; set; }
        public virtual ICollection<TiposProveedor> TiposProveedor { get; set; }
        public virtual ICollection<Zonas> Zonas { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
